# Generated by Django 3.2.11 on 2022-01-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20220118_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='Contact',
            field=models.CharField(max_length=100),
        ),
    ]
